### ISSUE TITLE
Header text needs some contrast 

### ISSUE THREAD

**Issue by dm4uz3** [RafaelDeJongh/h5ai-dark-theme#1]
![deepinscreenshot_select-area_20181022200735](https://user-images.githubusercontent.com/19360280/47313166-2872f280-d636-11e8-8bd2-11ea47a82ccd.png)

**Comment by dm4uz3** [comment]
add a _h5ai.header.md or .html in the directory. for a footer it's _h5ai.footer.md/html

**Comment by dm4uz3** [comment]
figured it out. all it needs is something like 
```css 
#content-header{color: #E9E9E9}
#content-footer{color: #E9E9E9}
```
